services:
  mysql-conatiner:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      mysql-networks:
        ipv4_address: 172.15.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ThisisDoriginDatabase
    volumes:
      - ../mysql:/var/lib/mysql
      - /tmp:/tmp
  my-server:
    image: server:latest
    container_name: my-server
    ports:
      - 8080:8080
    networks:
      mysql-networks:
        ipv4_address: 172.15.0.3
  my-client:
    image: client:latest
    container_name: my-client
    ports:
      - 3000:3000
    networks:
      mysql-networks:
        ipv4_address: 172.15.0.4
    volumes:
      - ../homepage/public:/app/public
  my-nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 3080:80
    networks:
      mysql-networks:
        ipv4_address: 172.15.0.5
    volumes:
      - ../homepage/public:/etc/nginx


networks:
  mysql-networks:
    name: mysql-networks
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16